<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>YtMusicController</AssemblyName>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\AppIcon.ico" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\YtMusicController.Core\YtMusicController.Core.csproj" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <ProjectReference Include="..\YtMusicController.WebView\YtMusicController.WebView.csproj" />
    <ProjectReference Include="..\YtMusicController.Api\YtMusicController.Api.csproj" />
  </ItemGroup>
</Project>
